---
- hosts: all
  tasks: 
  - name: instalar apache, mariabd, php
    apt: 
      name:
       - apache2
       - mariadb-server
       - mariadb-client
       - php 
       - libapache2-mod-php 
       - php-mysql
      state: present

  - name: crear usuario en maria db
    mysql_user:
        name: myapp
        password: mypass
        priv: '*.*:ALL,GRANT'
        state: present